(cl:defpackage turtlebot3_example-msg
  (:use )
  (:export
   "<TURTLEBOT3ACTION>"
   "TURTLEBOT3ACTION"
   "<TURTLEBOT3ACTIONFEEDBACK>"
   "TURTLEBOT3ACTIONFEEDBACK"
   "<TURTLEBOT3ACTIONGOAL>"
   "TURTLEBOT3ACTIONGOAL"
   "<TURTLEBOT3ACTIONRESULT>"
   "TURTLEBOT3ACTIONRESULT"
   "<TURTLEBOT3FEEDBACK>"
   "TURTLEBOT3FEEDBACK"
   "<TURTLEBOT3GOAL>"
   "TURTLEBOT3GOAL"
   "<TURTLEBOT3RESULT>"
   "TURTLEBOT3RESULT"
  ))

