; Auto-generated. Do not edit!


(cl:in-package turtlebot3_example-msg)


;//! \htmlinclude Turtlebot3Result.msg.html

(cl:defclass <Turtlebot3Result> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:string
    :initform ""))
)

(cl:defclass Turtlebot3Result (<Turtlebot3Result>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Turtlebot3Result>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Turtlebot3Result)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot3_example-msg:<Turtlebot3Result> is deprecated: use turtlebot3_example-msg:Turtlebot3Result instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <Turtlebot3Result>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtlebot3_example-msg:result-val is deprecated.  Use turtlebot3_example-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Turtlebot3Result>) ostream)
  "Serializes a message object of type '<Turtlebot3Result>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'result))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'result))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Turtlebot3Result>) istream)
  "Deserializes a message object of type '<Turtlebot3Result>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'result) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Turtlebot3Result>)))
  "Returns string type for a message object of type '<Turtlebot3Result>"
  "turtlebot3_example/Turtlebot3Result")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Turtlebot3Result)))
  "Returns string type for a message object of type 'Turtlebot3Result"
  "turtlebot3_example/Turtlebot3Result")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Turtlebot3Result>)))
  "Returns md5sum for a message object of type '<Turtlebot3Result>"
  "c22f2a1ed8654a0b365f1bb3f7ff2c0f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Turtlebot3Result)))
  "Returns md5sum for a message object of type 'Turtlebot3Result"
  "c22f2a1ed8654a0b365f1bb3f7ff2c0f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Turtlebot3Result>)))
  "Returns full string definition for message of type '<Turtlebot3Result>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%string result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Turtlebot3Result)))
  "Returns full string definition for message of type 'Turtlebot3Result"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%string result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Turtlebot3Result>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'result))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Turtlebot3Result>))
  "Converts a ROS message object to a list"
  (cl:list 'Turtlebot3Result
    (cl:cons ':result (result msg))
))
