#ifndef _ROBOT_MODEL_PARAM_H_
#define _ROBOT_MODEL_PARAM_H_



#define WHEEL_RADIUS		0.033
#define WHEEL_SEPARATION 	1
#define TURNING_RADIUS 1
#define ROBOT_RADIUS 1
#define ENCODER_MIN 1
#define ENCODER_MAX 1

#define MAX_LINEAR_VELOCITY 1
#define MAX_ANGULAR_VELOCITY 1

#define MIN_LINEAR_VELOCITY		0
#define MIN_ANGULAR_VELOCITY	1


#endif /* _ROBOT_MODEL_PARAM_H_ */
