#ifndef _ROBOT_MODEL_PARAM_H_
#define _ROBOT_MODEL_PARAM_H_



#define WHEEL_RADIUS		0.033
#define WHEEL_SEPARATION 	0.173
#define TURNING_RADIUS 		0.08
#define ROBOT_RADIUS 		0.1
#define ENCODER_MIN 		-2147483648
#define ENCODER_MAX 		2147483648

#define MAX_LINEAR_VELOCITY 	(WHEEL_RADIUS * 2 * 3.14159265359 * 60 / 60)
#define MAX_ANGULAR_VELOCITY 	(MAX_LINEAR_VELOCITY / TURNING_RADIUS)

#define MIN_LINEAR_VELOCITY		-MAX_LINEAR_VELOCITY
#define MIN_ANGULAR_VELOCITY	-MAX_ANGULAR_VELOCITY


#endif /* _ROBOT_MODEL_PARAM_H_ */
